"use client";

import { useState } from "react";
import { BarChart3, Bell, Cake, Check, ChevronDown, Coffee, Gift, Heart, House, MessageCircle, Plus, Settings, Sparkles, Stamp, Users, Wallet, Wifi } from "lucide-react";
import { Brand, DemoLoyaltyCard } from "./ui";

export function PhoneDemo() {
  const [count, setCount] = useState(4);
  const [wallet, setWallet] = useState("Apple Wallet");
  return <div className="m-phone-scene"><div className="m-orbit m-orbit-one" /><div className="m-orbit m-orbit-two" /><span className="m-phone-note">Siempre a mano <Heart size={20} /></span><div className="m-phone"><div className="m-phone-status"><span>9:41</span><span className="m-phone-island" /><span><Wifi size={13} /><span className="m-battery" /></span></div><div className="m-phone-content"><div className="m-phone-greeting"><Brand /><span>¡Hola, Sofi! <span aria-hidden="true">☀</span></span></div><h3>Un poquito más cerca<br />de tu próximo café.</h3><DemoLoyaltyCard count={count} /><div className="m-wallet-preview"><Wallet size={20} /><span>Vista previa en<strong>{wallet}</strong></span><Check size={17} /></div><p className="m-phone-progress" aria-live="polite">{count === 10 ? "¡Llegaste! Tu café gratis te espera." : `Te faltan ${10 - count} sellos para tu café gratis.`}</p><button className="m-demo-stamp" onClick={() => setCount(count === 10 ? 4 : count + 1)}>{count === 10 ? "Volver a probar" : <><Plus size={15} /> Probá sumar un sello</>}</button><span className="m-demo-caption">Demostración de la tarjeta</span></div><div className="m-phone-home" /></div><div className="m-wallet-switch" aria-label="Vista previa de la tarjeta">{["Apple Wallet", "Google Wallet"].map(item => <button key={item} aria-pressed={wallet === item} onClick={() => setWallet(item)} className={wallet === item ? "m-active" : ""}><Wallet size={15} />{item}</button>)}</div><div className="m-phone-notification"><span className="m-icon-circle"><Gift size={20} /></span><span><strong>Cada visita tiene algo lindo.</strong><small>Vos elegís la recompensa.</small></span></div></div>;
}

const dashboardItems = [[House, "Inicio"], [Users, "Clientes"], [Sparkles, "Promociones"], [Stamp, "Sellos"], [Gift, "Recompensas"], [MessageCircle, "Comunicaciones"], [BarChart3, "Estadísticas"], [Settings, "Configuración"]] as const;
const dashboardMetrics = [[Users, "Clientes registrados", "1.248", "+12,8%"], [Sparkles, "Promociones activas", "3", "En curso"], [Stamp, "Sellos otorgados", "8.532", "+18,4%"], [Gift, "Recompensas canjeadas", "320", "+8,2%"]] as const;
const recentCustomers = [["SL", "Sofía López", "Hace 5 min", "4 sellos"], ["MR", "Martín Rodríguez", "Hace 18 min", "8 sellos"], ["GP", "Gabriela Pérez", "Hace 32 min", "2 sellos"]] as const;
export function DashboardMetric({ icon: Icon, label, value, trend }: { icon: typeof Users; label: string; value: string; trend: string }) {
  return <div className="m-metric"><span><Icon size={15} />{label}</span><strong>{value}</strong><small>{trend} {trend !== "este mes" && <span>este mes</span>}</small></div>;
}
export function CustomerGrowthChart() {
  return <div className="m-chart"><div className="m-panel-title"><strong>Crecimiento de clientes</strong><span><i />Clientes</span></div><div className="m-chart-plot"><div className="m-chart-labels"><span>1.500</span><span>1.000</span><span>500</span><span>0</span></div><svg viewBox="0 0 500 160" preserveAspectRatio="none" role="img" aria-label="Gráfico ilustrativo de crecimiento de 500 a 1.248 clientes"><defs><linearGradient id="m-chart-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#FF1F2D" stopOpacity=".16" /><stop offset="100%" stopColor="#FF1F2D" stopOpacity="0" /></linearGradient></defs>{[15, 60, 105, 150].map(y => <line key={y} x1="0" x2="500" y1={y} y2={y} stroke="#eeeae7" strokeDasharray="4 5" />)}<path d="M0 135 C25 137 35 110 65 114 S105 118 130 94 S170 105 190 83 S220 95 250 64 S280 77 310 52 S345 68 370 42 S400 54 425 29 S465 32 500 8 L500 160 L0 160 Z" fill="url(#m-chart-fill)" /><path d="M0 135 C25 137 35 110 65 114 S105 118 130 94 S170 105 190 83 S220 95 250 64 S280 77 310 52 S345 68 370 42 S400 54 425 29 S465 32 500 8" fill="none" stroke="#FF1F2D" strokeWidth="3" /></svg></div><div className="m-chart-months"><span>Abr</span><span>May</span><span>Jun</span><span>Jul</span><span>Ago</span><span>Sep</span></div></div>;
}

export function Dashboard() {
  return <div className="m-dashboard" aria-label="Vista de ejemplo del panel de mimo"><aside className="m-dashboard-sidebar"><Brand /><span className="m-demo-store"><Coffee size={16} /><span>Café de la esquina<small>Mi comercio</small></span><ChevronDown size={12} /></span><div className="m-dashboard-menu">{dashboardItems.map(([Icon, text], i) => <span key={text} className={i === 0 ? "m-selected" : ""}><Icon size={15} />{text}</span>)}</div><div className="m-sidebar-bottom"><span className="m-avatar">M</span><span>María Fernández<small>Administradora</small></span></div></aside><div className="m-dashboard-main"><div className="m-dashboard-top"><span>Tu comercio, de un vistazo</span><span className="m-preview-label">VISTA DE EJEMPLO</span><Bell size={16} /></div><div className="m-dashboard-heading"><div><h3>¡Buen día, María! <span aria-hidden="true">☀</span></h3><p>Las buenas relaciones también se ven en los números.</p></div><span className="m-period">Últimos 30 días <ChevronDown size={12} /></span></div><div className="m-metrics">{dashboardMetrics.map(([Icon, label, value, trend]) => <DashboardMetric key={label} icon={Icon} label={label} value={value} trend={trend} />)}</div><div className="m-dashboard-panels"><CustomerGrowthChart /><div className="m-recent"><div className="m-panel-title"><strong>Últimos clientes</strong><Users size={14} /></div>{recentCustomers.map(([initials, name, time, stamps]) => <div className="m-recent-row" key={name}><span className="m-avatar">{initials}</span><span><strong>{name}</strong><small>{time}</small></span><span>{stamps}</span></div>)}</div></div><div className="m-dashboard-tip"><Heart size={14} /><span>Detrás de cada número, hay alguien que eligió volver.</span></div></div></div>;
}

const segments = ["Clientes frecuentes", "Clientes nuevos", "Clientes inactivos", "Cumpleaños del mes", "Clientes con 5+ sellos", "Recompensa disponible", "Recompensa canjeada"];
const customers = [
  { name: "Sofía López", initials: "SL", stamps: 8, visit: "Hoy", tags: [0, 4], label: "Frecuente" },
  { name: "Martín Rodríguez", initials: "MR", stamps: 6, visit: "Ayer", tags: [0, 4, 6], label: "Frecuente" },
  { name: "Gabriela Pérez", initials: "GP", stamps: 10, visit: "Hace 2 días", tags: [0, 3, 4, 5], label: "Cumpleaños" },
  { name: "Lucía Silva", initials: "LS", stamps: 1, visit: "Hoy", tags: [1], label: "Nueva" },
  { name: "Nicolás Castro", initials: "NC", stamps: 3, visit: "Hace 35 días", tags: [2], label: "Inactivo" },
];
export function Segmentation() {
  const [selected, setSelected] = useState(0);
  const filtered = customers.filter(c => c.tags.includes(selected));
  return <div className="m-segments-demo"><div className="m-segment-heading"><span><Users size={20} /><strong>Tus clientes, más cerca</strong></span><span className="m-preview-label">EJEMPLO INTERACTIVO</span></div><div className="m-segment-chips" aria-label="Filtrar clientes de ejemplo">{segments.map((segment, i) => <button key={segment} aria-pressed={selected === i} onClick={() => setSelected(i)} className={selected === i ? "m-chip-selected" : ""}>{i === 3 ? <Cake size={14} /> : i === 5 ? <Gift size={14} /> : <span className="m-chip-dot" />}{segment}</button>)}</div><div className="m-segment-table-wrap"><table className="m-segment-table"><thead><tr><th>Cliente</th><th>Última visita</th><th>Sellos</th><th>Segmento</th></tr></thead><tbody>{filtered.map(c => <tr key={c.name}><td><span className="m-avatar">{c.initials}</span><strong>{c.name}</strong></td><td>{c.visit}</td><td><Stamp size={13} /> {c.stamps}/10</td><td><span className="m-customer-tag">{c.label}</span></td></tr>)}</tbody></table></div><p className="m-segment-summary" aria-live="polite">{filtered.length} {filtered.length === 1 ? "cliente en este segmento" : "clientes en este segmento"} <span>Datos ilustrativos</span></p></div>;
}

