"use client";

import { useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Cake, Check, Coffee, Croissant, Dumbbell, Gift, Heart, IceCreamBowl, Menu, MessageCircle, Monitor, Plus, Scissors, ShoppingBag, SlidersHorizontal, Smartphone, Sparkles, Store, TrendingUp, UserRound, Users, Utensils, Wallet, Wifi, X } from "lucide-react";
import { Brand, CTA, Eyebrow, LoyaltyCard, Reveal } from "./ui";
import { Dashboard, PhoneDemo, Segmentation } from "./demos";
import { EarlyAccess, LegalDialog } from "./contact";

const navLinks = [["Cómo funciona", "como-funciona"], ["Para comercios", "para-comercios"], ["Beneficios", "beneficios"], ["Preguntas", "preguntas"]];
const faq = [
  ["¿El cliente tiene que descargar una app?", "No. Se registra desde el navegador de su celular y puede guardar su tarjeta de beneficios en Apple Wallet o Google Wallet. Sin otra app y sin contraseñas para recordar."],
  ["¿Cómo se agregan los sellos?", "Inicialmente se agregan desde el panel del comercio. Más adelante se podrán sumar opciones mediante QR o integraciones con sistemas de venta. Vos definís qué compra suma un sello."],
  ["¿Necesito cambiar mi sistema de caja?", "No. mimo funciona de forma independiente. Podés seguir usando tu sistema de caja y gestionar la fidelización desde el panel web."],
  ["¿Qué pasa si el cliente no tiene NFC?", "También puede ingresar mediante un código QR. El registro y la tarjeta digital funcionan igual desde el navegador."],
  ["¿Puedo crear mis propias recompensas?", "Sí. Cada comercio define su programa: cuántos sellos se necesitan y qué recompensa se obtiene. Puede ser un café, un descuento o ese beneficio que sabés que les encanta."],
  ["¿Puedo comunicarme con mis clientes?", "Sí. El sistema está pensado para permitir promociones, recordatorios y campañas segmentadas, con el consentimiento de tus clientes. Los canales y funciones disponibles se confirmarán durante el acceso anticipado."],
];
const merchantTypes = [[Coffee, "Cafeterías"], [Utensils, "Restaurantes"], [Croissant, "Panaderías"], [Scissors, "Peluquerías"], [ShoppingBag, "Tiendas"], [Dumbbell, "Gimnasios"]] as const;
const steps = [[Wifi, "Acercan el celular", "Un toque al soporte NFC del mostrador. También pueden usar el QR."], [UserRound, "Se registran una vez", "Nombre, cumpleaños, email y teléfono. Listo, ya son parte."], [Wallet, "Guardan su tarjeta", "Su tarjeta de beneficios, siempre a mano en Apple Wallet o Google Wallet."], [Gift, "Empiezan a sumar", "Cada compra puede ser un sello. Y cada sello, una razón para volver."]] as const;
const crmSmallCards = [[Heart, "A los que siempre vuelven", "Premiá a tus clientes más frecuentes."], [Gift, "Ya les falta poquito", "Avisales cuando están cerca de su recompensa."], [Sparkles, "La primera de muchas", "Convertí una primera visita en una segunda."]] as const;
const useCases = [[Coffee, "Cafeterías", "10 cafés → 1 gratis", "coffee"], [Utensils, "Restaurantes", "5 almuerzos → postre de regalo", "restaurant"], [Scissors, "Peluquerías", "5 visitas → 20% OFF", "salon"], [Croissant, "Panaderías", "8 compras → una merienda", "bakery"], [ShoppingBag, "Tiendas", "5 compras → un beneficio especial", "shop"], [Dumbbell, "Gimnasios", "12 clases → una clase de regalo", "gym"], [Sparkles, "Estéticas", "4 sesiones → un mimo extra", "beauty"], [IceCreamBowl, "Heladerías", "8 helados → 1 gratis", "icecream"]] as const;
const benefitItems = [[Heart, "Más clientes que vuelven", "Creá un motivo concreto para que esa visita no sea la última."], [Users, "Datos propios", "Construí una base de clientes que es tuya. Conocelos más allá del ticket."], [TrendingUp, "Más ventas recurrentes", "Activá a quienes dejaron de venir y reconocé a quienes siempre están."], [Smartphone, "Sin apps complicadas", "NFC + Wallet + web. Simple para tus clientes y para tu equipo."]] as const;

export default function Landing() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [legal, setLegal] = useState(null);
  return <div className="m-landing" id="inicio">
    <a className="m-skip-link" href="#contenido">Ir al contenido</a>
    <header className="m-header"><div className="m-container m-nav"><a href="#inicio" aria-label="mimo rewards, inicio"><Brand /></a><nav className="m-desktop-nav" aria-label="Navegación principal">{navLinks.map(([label, id]) => <a href={`#${id}`} key={id}>{label}</a>)}</nav><div className="m-nav-actions"><CTA /><button className="m-menu-toggle" aria-label={menuOpen ? "Cerrar menú" : "Abrir menú"} aria-expanded={menuOpen} aria-controls="m-mobile-nav" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={22} /> : <Menu size={22} />}</button></div></div><nav id="m-mobile-nav" className="m-mobile-nav" hidden={!menuOpen} aria-label="Navegación móvil" onKeyDown={e => { if (e.key === "Escape") { setMenuOpen(false); document.querySelector<HTMLButtonElement>(".m-menu-toggle")?.focus(); } }}>{navLinks.map(([label, id]) => <a href={`#${id}`} key={id} onClick={() => setMenuOpen(false)}>{label}<ArrowUpRight size={16} /></a>)}<Link href="/caja">Terminal Web de Caja</Link><Link href="/admin">Panel de Admin (CRM)</Link></nav></header>
    <main id="contenido">
      <section className="m-hero"><div className="m-container m-hero-grid"><Reveal className="m-hero-copy"><div className="m-launch-pill"><span /> FIDELIZACIÓN PARA COMERCIOS REALES</div><h1>Hacé que tus<br />clientes <span>vuelvan<svg viewBox="0 0 370 16" aria-hidden="true"><path d="M4 11 Q180 -4 364 9" /></svg></span><span className="m-hero-period">.</span></h1><p>Convertí cada compra en una razón para volver. Un soporte NFC, una tarjeta digital y todo lo que necesitás para estar más cerca de tus clientes.</p><div className="m-hero-actions"><CTA /><CTA secondary href="#como-funciona">Ver cómo funciona</CTA></div><div className="m-hero-trust"><span><Check size={14} /> Sin app para descargar</span><span><Wallet size={15} /> Apple Wallet y Google Wallet</span></div><a href="#acceso" className="m-early-note"><span className="m-early-avatars"><span>c</span><span><Coffee size={15} /></span><span><Scissors size={15} /></span></span><span>Para los comercios de todos los días.<br /><strong>Sumate al acceso anticipado <ArrowRight size={13} /></strong></span></a></Reveal><Reveal className="m-hero-visual"><div className="m-hero-image"><Image src="/images/mimo-identity-kit.webp" fill priority loading="eager" sizes="(max-width: 760px) 100vw, 52vw" alt="Soporte NFC rojo mimo rewards junto a un celular y un kit de bienvenida en una cafetería" /></div><div className="m-tap-label"><span className="m-icon-circle"><Wifi size={22} /></span><div><strong>Un toque. Y ya son parte.</strong><span>Así de simple empieza todo.</span></div><span className="m-tap-check"><Check size={13} /></span></div><div className="m-hero-floating-card"><LoyaltyCard mini /><span className="m-floating-wallet"><Wallet size={13} /> Del mostrador a su Wallet <Heart size={12} fill="currentColor" /></span></div><div className="m-hero-stat"><span className="m-stat-icon"><TrendingUp size={21} /></span><span>Tu comercio, más cerca<strong>+1 cliente que vuelve <Heart size={12} fill="currentColor" /></strong></span></div><span className="m-hero-caption">UNA EXPERIENCIA FÍSICA + DIGITAL</span></Reveal></div></section>
      <section className="m-business-strip" aria-label="Comercios para los que está pensado mimo"><div className="m-container"><p>Pequeños comercios.<br /><strong>Grandes relaciones.</strong></p><div>{merchantTypes.map(([Icon, label]) => <span key={label}><Icon size={23} strokeWidth={1.5} />{label}</span>)}</div></div></section>
      <section id="como-funciona" className="m-section m-how"><div className="m-container"><Reveal className="m-section-heading m-centered"><Eyebrow>MENOS PASOS, MÁS ENCUENTROS</Eyebrow><h2>Tus clientes se suman<br />en segundos.</h2><p>Vos seguís haciendo lo tuyo. mimo se encarga de conectar.</p></Reveal><div className="m-steps">{steps.map(([Icon, title, body], i) => <Reveal className="m-step" key={title}><div className="m-step-top"><span className="m-step-icon"><Icon size={29} strokeWidth={1.5} /></span><span className="m-step-number">0{i + 1}</span></div><h3>{title}</h3><p>{body}</p>{i < 3 && <span className="m-step-arrow"><ArrowRight size={17} /></span>}</Reveal>)}</div></div></section>
      <section className="m-section m-customer"><div className="m-container m-split"><Reveal><PhoneDemo /></Reveal><Reveal className="m-feature-copy"><Eyebrow>DEL LADO DE TUS CLIENTES</Eyebrow><h2>Su lugar favorito.<br />Ahora, también<br /> en su celular.</h2><p>Una tarjeta de fidelización que vive en su celular. Sin instalar otra app. Sin tarjetas de papel que se pierden.</p><p>Tus clientes guardan su tarjeta y consultan sus sellos y beneficios cuando quieran. Tu comercio va con ellos.</p><ul className="m-check-list">{["Apple Wallet y Google Wallet", "Sellos y recompensas", "Beneficios personalizados", "Una experiencia simple y rápida"].map(item => <li key={item}><span><Check size={13} /></span>{item}</li>)}</ul><a className="m-text-link" href="#acceso">Quiero esto para mi comercio <ArrowUpRight size={18} /></a></Reveal></div></section>
      <section id="para-comercios" className="m-merchant m-section"><div className="m-container"><Reveal className="m-merchant-heading"><div><Eyebrow light>DEL LADO DE TU COMERCIO</Eyebrow><h2>Conocé a los clientes<br />que vuelven.</h2></div><p>Mientras tus clientes acumulan beneficios, vos construís una base de datos propia para entender quién compra, quién vuelve y quién hace tiempo que no viene.</p></Reveal><Reveal><Dashboard /></Reveal><div className="m-dashboard-foot"><span><Check size={15} /> Tu base de clientes</span><span><Check size={15} /> Tu programa de beneficios</span><span><Check size={15} /> Todo en un mismo lugar</span></div><div className="m-existing-access"><span><Monitor size={18} /><span>¿Ya usás mimo? <strong>Entrá a tu espacio.</strong></span></span><div><Link href="/caja">Terminal Web de Caja <ArrowUpRight size={15} /></Link><Link href="/admin">Panel de Admin (CRM) <ArrowUpRight size={15} /></Link></div></div></div></section>
      <section className="m-section m-crm"><div className="m-container"><Reveal className="m-section-heading m-centered"><Eyebrow>LOS DATOS SE CONVIERTEN EN GESTOS</Eyebrow><h2>No es solo una<br />tarjeta de sellos.</h2><p>Cada registro te ayuda a conocer mejor a tus clientes<br className="m-desktop-break" /> y hablarles en el momento correcto.</p></Reveal><div className="m-crm-grid"><Reveal className="m-crm-card m-birthday"><span className="m-crm-icon"><Cake size={25} /></span><h3>Un mimo en su cumpleaños.</h3><p>Los pequeños detalles hacen que se acuerden de vos.</p><div className="m-message"><div><span className="m-message-brand"><Heart size={13} fill="currentColor" /></span><strong>Café de la esquina</strong><small>ahora</small></div><p>¡Feliz cumple, Gabi! <span aria-hidden="true">🎂</span><br />Tenés <strong>20% OFF</strong> esta semana.<br />Te esperamos para festejar.</p></div><span className="m-card-footnote">CUMPLEAÑOS · EJEMPLO DE MENSAJE</span></Reveal><Reveal className="m-crm-card m-inactive"><span className="m-crm-icon"><MessageCircle size={25} /></span><h3>Un «te extrañamos» a tiempo.</h3><p>Volvé a conectar con quienes hace un tiempito no vienen.</p><div className="m-message"><div><span className="m-message-brand"><Coffee size={13} /></span><strong>Café de la esquina</strong><small>ahora</small></div><p>Hace 30 días que no venís <span aria-hidden="true">👀</span><br />Tenemos algo para vos.<br />¿Nos tomamos un café?</p></div><span className="m-card-footnote">CLIENTES INACTIVOS · EJEMPLO DE MENSAJE</span></Reveal><Reveal className="m-crm-small-stack">{crmSmallCards.map(([Icon, title, text]) => <div className="m-crm-small" key={title}><span><Icon size={21} /></span><div><h3>{title}</h3><p>{text}</p></div></div>)}</Reveal></div><div className="m-segmentation m-split"><Reveal className="m-feature-copy"><Eyebrow>EL MENSAJE JUSTO, A LA PERSONA JUSTA</Eyebrow><h2>Segmentá.<br /> Sin complicarte.</h2><p>No todos tus clientes están en el mismo momento. Encontrá a cada grupo y pensá un beneficio que le den ganas de aprovechar.</p><span className="m-inline-note"><SlidersHorizontal size={17} /> Probá los filtros del ejemplo.</span></Reveal><Reveal><Segmentation /></Reveal></div></div></section>
      <section className="m-kit-section"><div className="m-container m-kit-grid"><Reveal className="m-kit-visual"><Image src="/images/mimo-identity-kit.webp" fill sizes="(max-width: 760px) 100vw, 50vw" alt="Kit mimo con soportes NFC rojos, sticker circular, tarjeta de bienvenida y packaging en una cafetería" /><span className="m-kit-image-label"><Wifi size={16} /> De tu mostrador a su próxima visita.</span></Reveal><Reveal className="m-kit-copy"><Eyebrow>CHICO EN TU MOSTRADOR. GRANDE EN TU NEGOCIO.</Eyebrow><h2>Todo empieza<br />en el mostrador.</h2><p>Colocás el soporte, el cliente acerca el celular y listo. Sin descargar apps ni escanear códigos complicados. Y si no tiene NFC, también hay QR.</p><div className="m-kit-contents"><span className="m-kit-label"><Store size={15} /> KIT PARA COMERCIO</span><ul>{["2 soportes NFC personalizados", "Configuración inicial", "Tarjeta digital para tus clientes", "Panel web para tu comercio", "Programa de fidelización", "Soporte para acompañarte"].map(item => <li key={item}><Check size={15} />{item}</li>)}</ul></div><a href="#acceso" className="m-text-link">Quiero mi kit mimo <ArrowUpRight size={18} /></a></Reveal></div></section>
      <section className="m-section m-ecosystem"><div className="m-container"><Reveal className="m-section-heading m-centered"><Eyebrow>TODO CONECTADO, TODO SIMPLE</Eyebrow><h2>Una experiencia. Dos lados.</h2><p>Simple para tus clientes. Valiosa para tu comercio.</p></Reveal><Reveal className="m-ecosystem-diagram"><div className="m-ecosystem-side"><span className="m-ecosystem-icon"><Smartphone size={27} /></span><h3>Un cliente contento</h3><span className="m-ecosystem-label">CLIENTE</span><div className="m-flow-tags">{["NFC / QR", "Registro", "Tarjeta digital", "Apple / Google Wallet", "Sellos y recompensas"].map(item => <span key={item}>{item}</span>)}</div></div><div className="m-ecosystem-center"><span className="m-connector-line" /><div><Brand /><Heart size={16} fill="currentColor" /></div><span className="m-connector-line" /></div><div className="m-ecosystem-side"><span className="m-ecosystem-icon"><Store size={27} /></span><h3>Un comercio que crece</h3><span className="m-ecosystem-label">COMERCIO</span><div className="m-flow-tags">{["Panel web", "Clientes y datos", "Promociones", "Recompensas", "Comunicaciones"].map(item => <span key={item}>{item}</span>)}</div></div></Reveal></div></section>
      <section className="m-section m-usecases"><div className="m-container"><Reveal className="m-section-heading"><Eyebrow>SI TUS CLIENTES VUELVEN, MIMO ES PARA VOS</Eyebrow><h2>Pensado para negocios<br />donde volver importa.</h2></Reveal><div className="m-usecase-grid">{useCases.map(([Icon, title, text, theme]) => <Reveal className={`m-usecase m-usecase-${theme}`} key={title}><div className="m-usecase-art"><Icon size={44} strokeWidth={1.3} /><span className="m-art-spark m-spark-one">✦</span><span className="m-art-spark m-spark-two">✧</span></div><h3>{title}</h3><p>{text}</p></Reveal>)}</div><p className="m-usecase-note">Algunas ideas para empezar. Las reglas y las recompensas las elegís vos.</p></div></section>
      <section id="beneficios" className="m-section m-benefits"><div className="m-container"><Reveal className="m-section-heading m-centered"><Eyebrow>BUENO PARA ELLOS. BUENO PARA VOS.</Eyebrow><h2>Más que fidelización.</h2></Reveal><div className="m-benefit-grid">{benefitItems.map(([Icon, title, text]) => <Reveal className="m-benefit" key={title}><span><Icon size={25} strokeWidth={1.6} /></span><h3>{title}</h3><p>{text}</p></Reveal>)}</div></div></section>
      <EarlyAccess onPrivacy={() => setLegal("privacy")} />
      <section id="preguntas" className="m-section m-faq"><div className="m-container m-faq-grid"><Reveal className="m-section-heading"><Eyebrow>TE LO HACEMOS SIMPLE</Eyebrow><h2>Quizás te estés<br />preguntando…</h2><p>Todo lo que necesitás saber<br />antes del primer mimo.</p><a className="m-text-link" href="#acceso">Conversemos <MessageCircle size={18} /></a></Reveal><div className="m-faq-list">{faq.map(([question, answer]) => <details key={question}><summary>{question}<Plus size={19} /></summary><p>{answer}</p></details>)}</div></div></section>
    </main>
    <footer className="m-footer"><div className="m-container"><div className="m-footer-top"><a href="#inicio" aria-label="mimo rewards, volver al inicio"><Brand /></a><p>Fidelización simple.<br />Relaciones que siguen.</p><nav aria-label="Enlaces del pie de página"><a href="#como-funciona">Cómo funciona</a><a href="#beneficios">Beneficios</a><a href="#acceso">Contacto</a><button onClick={() => setLegal("privacy")}>Privacidad</button><button onClick={() => setLegal("terms")}>Términos</button></nav></div><div className="m-footer-bottom"><span>© {new Date().getFullYear()} mimo rewards</span><span>Hecho con <Heart size={12} fill="currentColor" /> para los comercios de todos los días.</span><div><Link href="/caja">Caja <ArrowUpRight size={12} /></Link><Link href="/admin">Panel de Admin <ArrowUpRight size={12} /></Link></div></div></div></footer>
    {legal && <LegalDialog type={legal} close={() => setLegal(null)} />}
  </div>;
}
